export const lootboxItem = [
  {
    id: 1,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'primary',
  },
  {
    id: 2,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'primary',
  },
  {
    id: 3,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'primary',
  },
  {
    id: 4,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'secondary',
  },
  {
    id: 5,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'secondary',
  },
  {
    id: 6,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'secondary',
  },
  {
    id: 7,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'tertiary',
  },
  {
    id: 8,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'tertiary',
  },
  {
    id: 9,
    imageUrl: '/icons/energy.svg',
    title: ['gaming', 'energy'],
    value: 1500,
    type: 'tertiary',
  },
];
