export const giveawayItems = [
  {
    id: 1,
    order: 1,
    imageUrl: '/images/shared/lootbox',
    title: 'ENERGY GIFTBOX',
    type: 'RECEIVED',
  },
  {
    id: 2,
    order: 2,
    imageUrl: '/images/shared/lootbox',
    title: 'ENERGY GIFTBOX',
    description: 'until next level',
    points: 14020,
    type: 'FUTURE',
  },
  {
    id: 3,
    order: 3,
    imageUrl: '/images/shared/lootbox',
    title: 'ENERGY GIFTBOX',
    description: 'RECEIVE GIFT',
    buttonLabel: 'claim',
    type: 'ENDED',
  },
  {
    id: 4,
    order: 4,
    imageUrl: '/images/shared/lootbox',
    title: 'ENERGY GIFTBOX',
    description: 'until next level',
    points: 14020,
    type: 'FUTURE',
  },
  {
    id: 5,
    order: 5,
    imageUrl: '/images/giveaway/iphone',
    title: 'IPHONE 17 GIVEAWAY',
    description: 'until next level',
    points: 14020,
    label: 'GIVEAWAY',
    type: 'HOT',
  },
  {
    id: 6,
    order: 6,
    imageUrl: '/images/giveaway/iphone',
    title: 'IPHONE 17 GIVEAWAY',
    description: 'PARTICIPATE',
    buttonLabel: 'PARTICIPATE',
    label: 'GIVEAWAY',
    type: 'HOT',
  },
  {
    id: 7,
    order: 7,
    imageUrl: '/images/shared/lootbox',
    title: 'GIFTBOX GIVEAWAY',
    participating: 'YOU ARE PARTICIPATING',
    label: 'GIVEAWAY',
    type: 'HOT',
  },
];
